# A simple math problem for first grade

In [1]:
import numpy as np

In [2]:
A = np.matrix('1 1 0; 0 1 1; 1 0 1')

In [3]:
A

matrix([[1, 1, 0],
        [0, 1, 1],
        [1, 0, 1]])

In [4]:
v1=np.matrix('6; 7; 9')

In [5]:
v1

matrix([[6],
        [7],
        [9]])

## Inversion of the matrix gives the solution

In [6]:
invA = np.linalg.inv(A)

In [7]:
invA

matrix([[ 0.5, -0.5,  0.5],
        [ 0.5,  0.5, -0.5],
        [-0.5,  0.5,  0.5]])

### Solution to the initial problem

In [8]:
invA.dot(v1)

matrix([[ 4.],
        [ 2.],
        [ 5.]])

### Solution to a more complicated problem

In [9]:
v2=np.matrix('15; 13; 18')

In [10]:
invA.dot(v2)

matrix([[ 10.],
        [  5.],
        [  8.]])